### ISSUE TITLE
fatal design flaw

### ISSUE THREAD

**Issue by jbauernberger** [PACTCare/Dweb.page#2]
This looks like a great project and I am glad you have been thinking about decentralization. I have some issues with this though (only one really). It is built on IOTA. 

IOTA run by people (come_from_beyond and other questionable characters whose understanding of Math can best be summed up as "Numberwang"). People who think that collision resistance doesn't have to be a primary feature of a hash functions.

the IOTA guys have been ignorant towards any criticism from the cryptography experts (ask Matthew D. Green and many others).  IOTA is a total clusterfuck. Don't use it. Or if you do please check at least twitter to see what people with an actual idea of cryptography are saying.

Please consider rewriting this or alternatively push your commits to /dev/null ... thanks.

https://twitter.com/peterktodd/status/938397135862714373

https://twitter.com/matthew_d_green/status/1027197175456034818

https://twitter.com/dionyziz/status/968088282457354240

PS: crypto means cryptography

**Comment by tom-james-watson** [comment]
This is not how you constructively interact with an open source project.

**Comment by Felandil** [comment]
Hey @jbauernberger !

Would you mind elaborating your points? While being open to constructive criticism I myself don't consider twitter as a valid source of information, but rather like to see scientific proof. I'd be pleased if you were able to cite such sources.

Anyway I am well aware that there have been some rumors about a year ago. I'd request you to deepen my understanding of why they are relevant for this project and how they are an issue.

Please take into account that:
- The rumors were about IOTAs signing scheme for transactions that carry value
- The dWeb project does not use any transactions carrying value
- The dWeb project does not on rely nor even use the IOTA signing scheme 

In addition please make a proposal what the alternative would be. 
Please take into account that:
- A decentralized approach is needed
- A feeless approach is mandatory

**Comment by Noc2** [comment]
I’m closing this issue, since the complain is about a feature of IOTA, which is on the one hand fixed by IOTA and on the other hand not even  integrated in Dweb.page. But in general I welcome any kind of discussion here!
