### ISSUE TITLE
Actually the new version is broken in a different way, If I try to enter something to the search box, doesn't show any results but downloads file called "undefined.undefined" with content "invalid ipfs path: selected encoding not supported"

### ISSUE THREAD

**Issue by Noc2** [PACTCare/Dweb.page#6]
Actually the new version is broken in a different way, If I try to enter something to the search box, doesn't show any results but downloads file called "undefined.undefined" with content "invalid ipfs path: selected encoding not supported"
(browser chrome,  using private ipfs gateway running go-ipfs v0.4.18, ipfs companion v 2.6.3)

_Originally posted by @pezinek in https://github.com/PACTCare/Dweb.page/issues/5#issuecomment-455486788_

**Comment by Noc2** [comment]
@pezinek. Thanks for reporting. Are you using [QmYp7xKoZkKGjLkfQTdJoXpB4okpcx9UjGWavREvZkByro](https://ipfs.sopinka.com/ipfs/QmYp7xKoZkKGjLkfQTdJoXpB4okpcx9UjGWavREvZkByro)? And what do you enter inside the search field and how do you open this (press enter, click the open button)? I’m asking because I’m not having this issue with the same setup. 
Something I’m aware of is that the new availability system (name-based system combined with a location-based system for faster loading) doesn’t work if the companion is enabled because it replaces all ipfs links automatically. The best way currently is still do just make the local gateway writable (ipfs daemon –writable) and disable the companion, but I keep working on it.

**Comment by pezinek** [comment]
yes I'm using http://192.168.1.70:8080/ipfs/QmYp7xKoZkKGjLkfQTdJoXpB4okpcx9UjGWavREvZkByro
I enter "foo" in the search box and hit enter, the developer console then displays:
```
VM70:1 GET http://192.168.1.70:8080/ipfs/na 400 (Bad Request)
(anonymous) @ VM70:1
(anonymous) @ VM81 QmYp7xKoZkKGjLkfQTdJoXpB4okpcx9UjGWavREvZkByro:38
A @ VM81 QmYp7xKoZkKGjLkfQTdJoXpB4okpcx9UjGWavREvZkByro:21
(anonymous) @ VM81 QmYp7xKoZkKGjLkfQTdJoXpB4okpcx9UjGWavREvZkByro:21
t.(anonymous function) @ VM81 QmYp7xKoZkKGjLkfQTdJoXpB4okpcx9UjGWavREvZkByro:21
G @ VM81 QmYp7xKoZkKGjLkfQTdJoXpB4okpcx9UjGWavREvZkByro:38
a @ VM81 QmYp7xKoZkKGjLkfQTdJoXpB4okpcx9UjGWavREvZkByro:38
(anonymous) @ VM81 QmYp7xKoZkKGjLkfQTdJoXpB4okpcx9UjGWavREvZkByro:38
(anonymous) @ VM81 QmYp7xKoZkKGjLkfQTdJoXpB4okpcx9UjGWavREvZkByro:38
gt @ VM81 QmYp7xKoZkKGjLkfQTdJoXpB4okpcx9UjGWavREvZkByro:38
(anonymous) @ VM81 QmYp7xKoZkKGjLkfQTdJoXpB4okpcx9UjGWavREvZkByro:38
(anonymous) @ VM81 QmYp7xKoZkKGjLkfQTdJoXpB4okpcx9UjGWavREvZkByro:38
```
btw. disabling ipfs companion doesn't really make any difference in chrome, however if I change IPFS gateway to something else e.g. https://cloudflare-ipfs.com/ipfs/QmYp7xKoZkKGjLkfQTdJoXpB4okpcx9UjGWavREvZkByro and reload everything with disabled ipfs companion it works fine, and is broken with companion enabled. As well firefox works fine even via my private gateway (I don't have companion installed in firefox).

**Comment by pezinek** [comment]
... actually seems that even in firefox if I go to
http://192.168.1.70:8080/ipfs/QmYp7xKoZkKGjLkfQTdJoXpB4okpcx9UjGWavREvZkByro
and search for something strange like "strangelongstringthatwontmatchanything" then a 
file named undefined-1.undefined and it's content is again "invalid ipfs path: selected encoding not supported"

**Comment by pezinek** [comment]
... and just for completeness, right after loading dweb.page in chrome (even with companion disabled) I get following exception which may or may not be related to the search problems above:
```
Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
ad_status.js:1 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
VM42 QmYp7xKoZkKGjLkfQTdJoXpB4okpcx9UjGWavREvZkByro:21 Uncaught (in promise) TypeError: Cannot read property 'importKey' of undefined
    at t.<anonymous> (VM42 QmYp7xKoZkKGjLkfQTdJoXpB4okpcx9UjGWavREvZkByro:21)
    at A (VM42 QmYp7xKoZkKGjLkfQTdJoXpB4okpcx9UjGWavREvZkByro:21)
    at Generator._invoke (VM42 QmYp7xKoZkKGjLkfQTdJoXpB4okpcx9UjGWavREvZkByro:21)
    at Generator.t.(anonymous function) [as next] (http://192.168.1.70:8080/ipfs/QmYp7xKoZkKGjLkfQTdJoXpB4okpcx9UjGWavREvZkByro:21:361191)
    at p (VM42 QmYp7xKoZkKGjLkfQTdJoXpB4okpcx9UjGWavREvZkByro:21)
    at a (VM42 QmYp7xKoZkKGjLkfQTdJoXpB4okpcx9UjGWavREvZkByro:21)
    at VM42 QmYp7xKoZkKGjLkfQTdJoXpB4okpcx9UjGWavREvZkByro:21
    at new Promise (<anonymous>)
    at t.<anonymous> (VM42 QmYp7xKoZkKGjLkfQTdJoXpB4okpcx9UjGWavREvZkByro:21)
    at t.<anonymous> (VM42 QmYp7xKoZkKGjLkfQTdJoXpB4okpcx9UjGWavREvZkByro:21)
```

**Comment by Noc2** [comment]
The new online version https://ipfs.sopinka.com/ipfs/QmbgNNR3699h1yya11S1yrfmpCHj5npZu3wxJMVXPYLotK/ hopefully has fixed this issue. I also found a way to integrate the new availability system for faster loading. Feel free to comment here again, if it doesn’t work for you and I will reopen the issue.
